name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to the server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            # Pull the latest code
            if [ ! -d "/home/ubuntu/RubezhOS.git" ]; then
              echo "Repository not found. Cloning..."
              git clone https://glebmavi:${{ secrets.GH_ACCESS_TOKEN }}@github.com/glebmavi/RubezhOS.git /home/ubuntu/RubezhOS
            else
              echo "Repository found. Pulling latest changes..."
              git pull https://glebmavi:${{ secrets.GH_ACCESS_TOKEN }}@github.com/glebmavi/RubezhOS.git /home/ubuntu/RubezhOS
            fi

            cd /home/ubuntu/RubezhOS
            # Build and run the Docker container
            docker-compose down
            docker-compose up --build -d
          EOF
